Test/ViewModels/BooksModel.cs
using Model.Model;

namespace Test.ViewModels
{
    public class BooksModel
    {
        public IEnumerable<Book> AvailableBooks { get; set; }
        public IEnumerable<Book> BorrowerBooks { get; set; }
    }
}

Test/Controllers/BookController.cs
using BusinessLogic.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Model.Model;
using System.Security.Claims;
using Test.ViewModels;

namespace Test.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService _bookService;
        private readonly IBookLoanService _bookLoanService;
        public BookController(IBookService bookService, IBookLoanService bookLoanService)
        {
            _bookService = bookService;
            _bookLoanService = bookLoanService;
        }
        public IActionResult Storage()
        {
            var books = _bookService.GetAllBooks();

            return View(books);
        }
        public IActionResult Books()
        {
            var books = _bookService.GetAllBooks();

            return View(books);
        }
        public IActionResult AvailableBook()
        {
            int userId = GetUserIdClaim();

            var availableBooks = _bookService.GetAvailableBook();
            var borrowerBooks = _bookLoanService.GetBorrowerBookLoans(userId);

            var booksModel = new BooksModel
            {
                AvailableBooks = availableBooks,
                BorrowerBooks = borrowerBooks
            };

            return View("Books", booksModel);
        }
        public IActionResult CreateBook()
        {
            return View("CreateBook");
        }

        [HttpPost]
        public IActionResult Create(Book book)
        {
            if (ModelState.IsValid)
            {
                _bookService.CreateBook(book);
                return RedirectToAction("AvailableBook", "Book");
            }
            return View("CreateBook", book);
        }
        public IActionResult TakeBook(int id)
        {
            try
            {
                int userId = GetUserIdClaim();

                _bookService.TakeBook(id, userId);

                return RedirectToAction("AvailableBook", "Book");
            }
            catch (Exception)
            {
                ViewData["ErrorMessage"] = "Данная книга отсутсвует";
                return View("Error");
            }
        }
        public IActionResult ReturnBook(int id)
        {
            try
            {
                _bookService.ReturnBook(id);
                return RedirectToAction("AvailableBook", "Book");
            }
            catch (Exception)
            {
                ViewData["ErrorMessage"] = "У вас нет такой книги";
                return View("Error");
            }
        }
        private int GetUserIdClaim()
        {
            ClaimsPrincipal currentUser = this.User;

            Claim userIdClaim = currentUser.FindFirst(ClaimTypes.NameIdentifier);

            int userId = int.Parse(userIdClaim.Value);

            return userId;
        }
    }
}

Test/Controllers/BookLoanController.cs
using BusinessLogic.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Model.Model;

namespace Test.Controllers
{
    public class BookLoanController : Controller
    {
        private readonly IBookLoanService _bookLoanService;

        public BookLoanController(IBookLoanService bookLoanService)
        {
            _bookLoanService = bookLoanService;
        }

        public IActionResult Accounting()
        {
            var loans = _bookLoanService.GetAllBookLoans();
            return View(loans);
        }
    }
}

Test/Controllers/UserController.cs
using BusinessLogic.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Model.Model;
using System.Security.Claims;

namespace Test.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }
        public IActionResult Readers()
        {
            var users = _userService.GetAllUsers();
            return View(users);
        }
        public IActionResult Index()
        {
            var users = _userService.GetAllUsers();
            return View(users);
        }
        public IActionResult RegisterUser()
        {
            return View();
        }
        [HttpGet("login")]
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Registration(User user)
        {
            try
            {
                    _userService.CreateUser(user);
                    return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ViewData["ErrorMessage"] = "Произошла ошибка при регистрации пользователя.";
                return View("Error");
            }
        }
        [HttpPost("login")]
        public IActionResult Login(string selectedLastName)
        {
            var user = _userService.GetUserByLastName(selectedLastName);

            if (user != null)
            {
                var claims = new List<Claim>
                 {
                     new Claim(ClaimTypes.Name, user.LastName),
                      new Claim(ClaimTypes.NameIdentifier, user.Id.ToString())
                 };

                var identity = new ClaimsIdentity(claims, "Cookies");

                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity));

                return RedirectToAction("AvailableBook", "Book");
            }
            else
            {
                throw new Exception("Пользователь не найден в систему");
            }
        }
        public IActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index");
        }
    }
}

Test/Views/Book/Books.cshtml
@model Test.ViewModels.BooksModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Доступные книги";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <h2 class="text-center">Доступные книги</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Код книги</th>
                <th>Название</th>
                <th>Автор</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var book in Model.AvailableBooks)
            {
             
                    <tr>
                        <td>@book.Id</td>
                        <td>@book.Name</td>
                        <td>@book.Author</td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="container mt-5">
    <h2 class="text-center">Мои книги</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Код книги</th>
                <th>Название</th>
                <th>Автор</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var book in Model.BorrowerBooks)
            {
                <tr>
                    <td>@book.Id</td>
                    <td>@book.Name</td>
                    <td>@book.Author</td>
                </tr>
            }
        </tbody>
    </table>
</div>
<form method="post" action="@Url.Action("TakeBook", "Book")" class="mt-3">
    <div class="form-group">
        <label for="takeBookId">ID книги для взятия:</label>
        <input type="text" class="form-control" id="takeBookId" name="id">
    </div>
    <button type="submit" class="btn btn-primary">Взять книгу</button>
</form>

<form method="post" action="@Url.Action("ReturnBook", "Book")" class="mt-3">
    <div class="form-group">
        <label for="returnBookId">ID книги для сдачи:</label>
        <input type="text" class="form-control" id="returnBookId" name="id">
    </div>
    <button type="submit" class="btn btn-primary">Сдать книгу</button>
</form>

<a href="@Url.Action("CreateBook", "Book")" class="btn btn-success mt-3" target="_blank">Добавить книгу</a>

<a href="@Url.Action("Readers", "User")" class="btn btn-success mt-3" target="_blank">Читатели</a>

<a href="@Url.Action("Accounting", "BookLoan")" class="btn btn-success mt-3" target="_blank">Выдача книг</a>

<a href="@Url.Action("Storage", "Book")" class="btn btn-success mt-3" target="_blank">Хранение книг</a>

Test/Views/Book/CreateBook.cshtml
@model Model.Model.Book
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Создание книги";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center">Создание новой книги</h2>
                    <form asp-action="Create" method="post">
                        <div class="form-group">
                            <label asp-for="Name">Название книги:</label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Author">Автор:</label>
                            <input asp-for="Author" class="form-control" />
                            <span asp-validation-for="Author" class="text-danger"></span>
                        </div>
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Создать книгу</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Test/Views/Book/Storage.cshtml
@model IEnumerable<Model.Model.Book>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Все книги";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <h2 class="text-center">Доступные книги</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Код книги</th>
                <th>Название</th>
                <th>Автор</th>
                <th>Доступность</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var book in Model)
            {

                <tr>
                    <td>@book.Id</td>
                    <td>@book.Name</td>
                    <td>@book.Author</td>
                    <td>
                        @(book.IsAvailable ? "Доступна" : "Не доступна")
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Test/Views/BookLoan/Accounting.cshtml
@model IEnumerable<Model.Model.BookLoan>
@{
    ViewData["Title"] = "Учет книг";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <h2 class="text-center">Учет книг</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Название книги</th>
                <th>Читатель</th>
                <th>Дата взятия</th>
                <th>Дата возврата</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var bookLoan in Model)
            {
                <tr>
                    <td>@bookLoan.Book.Name</td>
                    <td>@bookLoan.User.LastName</td>
                    <td>@bookLoan.LoanDate</td>
                    <td>@bookLoan.ReturnDate</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Test/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Test.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="/">Библиотека</a>
            </div>

            @if (User.Identity.IsAuthenticated)
            {
                <form asp-action="Logout" asp-controller="User" method="post" class="form-inline">
                    <button type="submit" class="btn btn-outline-danger">Выйти</button>
                </form>
            }
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Test/Views/User/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<Model.Model.User>

@{
    ViewData["Title"] = "Библиотека";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center">Добро пожаловать в библиотеку</h2>
                    <form method="post" action="@Url.Action("Login", "User")">
                        <div class="form-group">
                            <label for="LastName">Фамилия:</label>
                            <select class="form-control" id="LastName" name="selectedLastName">
                                @foreach (var user in Model)
                                {
                                    <option>@user.LastName</option>
                                }
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary btn-lg btn-block mt-3">Войти</button>
                    </form>
                    <p class="text-center mt-3">Если вашей фамилии нет в списке, вы можете зарегистрироваться:</p>
                    <a asp-action="RegisterUser">Зарегистрироваться</a>
                </div>
            </div>
        </div>
    </div>
</div>

Test/Views/User/Readers.cshtml
@model IEnumerable<Model.Model.User>
@{
    ViewData["Title"] = "Читатели";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <h2 class="text-center">Читатели</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Имя</th>
                <th>Отчество</th>
                <th>Фамилия</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model)
            {
                <tr>
                    <td>@user.Name</td>
                    <td>@user.MiddleName</td>
                    <td>@user.LastName</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Test/Views/User/RegisterUser.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model Model.Model.User

@{
    ViewData["Title"] = "Библиотека";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Регистрация читателя</h2>

<form asp-action="Registration">
    <div class="form-group">
        <label asp-for="LastName">Фамилия:</label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Name">Имя:</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="MiddleName">Отчество:</label>
        <input asp-for="MiddleName" class="form-control" />
        <span asp-validation-for="MiddleName" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
</form>